name: phpunit
on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        php-versions: [ '8.1' ]
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: PHP version check
        run: php -v
      - name: Composer install
        run: composer install --prefer-dist --no-interaction  --no-progress --no-suggest
      - name: Run tests
        run: vendor/bin/phpunit
